replicaCount: 2

image:
  repository: 230367374156.dkr.ecr.us-east-1.amazonaws.com/platform-services
  tag: scheduling-server-${release.tag}
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: private-miq-nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  paths:
    - /
  hosts:
    - scheduling.mediaiqdigital.com
    - scheduling.prod.miqdigital.com
  tls: []

config:
  application:
    messagingPublishEndpoint: "https://messaging-gateway.prod.miqdigital.com/publish"
    messagingDefaultPublishTopic: "production-scheduling-pub"
  environment: production
  spring:
    datasource:
      url: jdbc:postgresql://prod-techbrew-shared.cmfydxrklw15.us-east-1.rds.amazonaws.com:5432/scheduling_production
      username: miq_admin
      instanceName: QuartzPostgresScheduler_PRODUCTION
      quartzdatasourcename: quartzDataSource-PRODUCTION

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 512Mi

annotations:
  prometheus.io/env: "PRODUCTION"
  miq.io/javautils-webhook-s3-path: "s3://miq-techbrew/services/dumps/scheduling-service/production"
  vault.hashicorp.com/auth-path: "auth/kubernetes-prod"
  vault.hashicorp.com/role: "pt-scheduling-production"
  vault.hashicorp.com/agent-inject-secret-secrets.properties: "Platform-Vault-Kubernetes/data/scheduling-service-production"
  vault.hashicorp.com/agent-inject-template-secrets.properties: |
    {{- with secret "Platform-Vault-Kubernetes/data/scheduling-service-production" }}
      {{ range $k, $v := .Data.data }}
      {{- $k }}={{ $v }}
      {{ end }}
    {{- end }}

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - scheduling-service-production
        topologyKey: "failure-domain.beta.kubernetes.io/zone"

timestamp: A100

istio:
  enabled: false