replicaCount: 2

image:
  repository: 836079437595.dkr.ecr.us-east-1.amazonaws.com/platform-services
  tag: scheduling-server-${release.tag}${build.number}
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: private-nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  paths:
    - /
  hosts:
    - pr-scheduling.mediaiqdigital.com
  tls: []

config:
  environment: pr
  spring:
    datasource:
      url: jdbc:postgresql://techbrew-non-prod.cvb1rjfllvqw.us-east-1.rds.amazonaws.com:5432/scheduling_pr
      instanceName: QuartzPostgresScheduler_PR
      quartzdatasourcename: quartzDataSource-PR

annotations:
  prometheus.io/env: "PR"
  miq.io/javautils-webhook-s3-path: "s3://miq-dev-techbrew/services/dumps/scheduling-service/pr"
  vault.hashicorp.com/role: "pt-scheduling-pr"
  vault.hashicorp.com/agent-inject-secret-secrets.properties: "Platform-Vault-Kubernetes/data/scheduling-service-pr"
  vault.hashicorp.com/agent-inject-template-secrets.properties: |
    {{- with secret "Platform-Vault-Kubernetes/data/scheduling-service-pr" }}
      {{ range $k, $v := .Data.data }}
      {{- $k }}={{ $v }}
      {{ end }}
    {{- end }}

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - scheduling-service-pr
        topologyKey: "failure-domain.beta.kubernetes.io/zone"

timestamp: A100

istio:
  enabled: false