apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "scheduling-service.fullname" . }}-configuration
  labels:
    app.kubernetes.io/name: {{ include "scheduling-service.name" . }}
    helm.sh/chart: {{ include "scheduling-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- (tpl (.Files.Glob "config/*").AsConfig . ) | nindent 2 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "scheduling-service.fullname" . }}-environment
  labels:
    app.kubernetes.io/name: {{ include "scheduling-service.name" . }}
    helm.sh/chart: {{ include "scheduling-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ toYaml .Values.env | indent 2 }}