apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduling-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "scheduling-service.name" . }}
    helm.sh/chart: {{ include "scheduling-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.jacocoEnabled | default false }}
    - port: 36320
      targetPort: jacoco-port
      protocol: TCP
      name: jacoco-port
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "scheduling-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
