{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "scheduling-mockservices.serviceAccountName" . }}
  labels:
{{ include "scheduling-mockservices.labels" . | indent 4 }}
{{- end -}}
